const routes = {
  Registration:`register/`,
  Login:`login/`,
  Logout:`accounts/logout_user/`,
  Jobs:`/jobs/get_jobs/`,
  Refresh: '/accounts/token/refresh/',
  User: 'user/',
  Applications: '/jobs/get_applications/',
  Add_Job: '/jobs/add_job/',
  Update_Job: 'jobs/update_job/',
  Hr_View: '/jobs/hrview/',
  Add_Appplication: '/jobs/add_application/',
  Update_Application: '/jobs/update_application/',
  Teamlead_View: '/jobs/team_lead_view/',
  Accounts_View: '/jobs/account_view/',
  Admin_Add_Job: '/jobs/add_job/',
  Admin_Update_Job: '/jobs/update_job/',
  Admin_Delete_Job: '/jobs/delete_job/',
  Tasks: '/jobs/get_tasks/',
  Add_New_Task: '/jobs/add_new_task/',
  Update_Task: '/jobs/update_task/',
  Delete_Task: '/jobs/delete_task/',
  Meeting: '/jobs/meeting/',
  Teams: '/jobs/teams/',
  Projects: '/jobs/project/',
  User_Profile: 'profile/',
  User_Details: 'hruser/',
  FormSubmit_URL: 'https://formsubmit.co/ajax/',
}


export { routes };